#!/bin/bash

set -xe

bucket=$1
[[ -z $bucket ]] && echo 'bucket not provided' >&2 && exit 1

# /data in the container is bind mounted to /docker-run/database in the root fs
media_dir=$(/usr/bin/docker volume inspect -f "{{.Mountpoint}}" kv_media)

/usr/local/bin/aws s3 sync $media_dir s3://${bucket}/
