# THIS FILE IS GENERATED FROM models/../models/generate.sh
# DO NOT EDIT THIS FILE!
# This code parses date/times, so please
#
#     pip install python-dateutil
#
# To use this code, make sure you
#
#     import json
#
# and then, to convert JSON from a string, do
#
#     result = insurance_policy_from_dict(json.loads(json_string))
#     result = party_from_dict(json.loads(json_string))
#     result = lease_from_dict(json.loads(json_string))
#     result = user_from_dict(json.loads(json_string))
#     result = mongo_doc_from_dict(json.loads(json_string))
#     result = media_from_dict(json.loads(json_string))
#     result = property_from_dict(json.loads(json_string))
#     result = common_from_dict(json.loads(json_string))
#     result = note_from_dict(json.loads(json_string))
#     result = collection_name_from_dict(json.loads(json_string))

from dataclasses import dataclass
from typing import Any, Optional, List, Dict, TypeVar, Callable, Type, cast
from datetime import datetime
from enum import Enum
import dateutil.parser


T = TypeVar("T")
EnumT = TypeVar("EnumT", bound=Enum)


def from_str(x: Any) -> str:
    assert isinstance(x, str)
    return x


def from_none(x: Any) -> Any:
    assert x is None
    return x


def from_union(fs, x):
    for f in fs:
        try:
            return f(x)
        except:
            pass
    assert False


def from_datetime(x: Any) -> datetime:
    return dateutil.parser.parse(x)


def from_list(f: Callable[[Any], T], x: Any) -> List[T]:
    assert isinstance(x, list)
    return [f(y) for y in x]


def to_class(c: Type[T], x: Any) -> dict:
    assert isinstance(x, c)
    return cast(Any, x).to_dict()


def to_enum(c: Type[EnumT], x: Any) -> EnumT:
    assert isinstance(x, c)
    return x.value


def from_float(x: Any) -> float:
    assert isinstance(x, (float, int)) and not isinstance(x, bool)
    return float(x)


def to_float(x: Any) -> float:
    assert isinstance(x, float)
    return x


def from_int(x: Any) -> int:
    assert isinstance(x, int) and not isinstance(x, bool)
    return x


def from_dict(f: Callable[[Any], T], x: Any) -> Dict[str, T]:
    assert isinstance(x, dict)
    return { k: f(v) for (k, v) in x.items() }


def from_bool(x: Any) -> bool:
    assert isinstance(x, bool)
    return x


@dataclass
class OID:
    """A JSON-encoded BSON ObjectId
    
    The id of the user that created this object
    
    The id of the user that last modified this object
    """
    oid: str

    @staticmethod
    def from_dict(obj: Any) -> 'OID':
        assert isinstance(obj, dict)
        oid = from_str(obj.get("$oid"))
        return OID(oid)

    def to_dict(self) -> dict:
        result: dict = {}
        result["$oid"] = from_str(self.oid)
        return result


@dataclass
class InsurancePolicy:
    """An insurance policy that applies to one or more properties"""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    description: Optional[str]
    end_date: Optional[datetime]
    media_ids: Optional[List[OID]]
    start_date: Optional[datetime]

    @staticmethod
    def from_dict(obj: Any) -> 'InsurancePolicy':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        description = from_union([from_str, from_none], obj.get("description"))
        end_date = from_union([from_datetime, from_none], obj.get("endDate"))
        media_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("mediaIds"))
        start_date = from_union([from_datetime, from_none], obj.get("startDate"))
        return InsurancePolicy(error, id, created_by, created_date, last_modified_by, modified_date, description, end_date, media_ids, start_date)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["description"] = from_union([from_str, from_none], self.description)
        result["endDate"] = from_union([lambda x: x.isoformat(), from_none], self.end_date)
        result["mediaIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.media_ids)
        result["startDate"] = from_union([lambda x: x.isoformat(), from_none], self.start_date)
        return result


@dataclass
class Note:
    """A note that gives an update on an item"""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    media: Optional[List[OID]]
    note: Optional[str]
    title: Optional[str]

    @staticmethod
    def from_dict(obj: Any) -> 'Note':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        media = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("media"))
        note = from_union([from_str, from_none], obj.get("note"))
        title = from_union([from_str, from_none], obj.get("title"))
        return Note(error, id, created_by, created_date, last_modified_by, modified_date, media, note, title)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["media"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.media)
        result["note"] = from_union([from_str, from_none], self.note)
        result["title"] = from_union([from_str, from_none], self.title)
        return result


class TypeEnum(Enum):
    COMPANY = "company"
    PERSON = "person"


@dataclass
class Party:
    """A person or organization/company that interacts with real estate in some way, e.g. owner,
    lessee, contractors, etc.
    """
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    address: Optional[str]
    city: Optional[str]
    name: Optional[str]
    notes: Optional[Note]
    phone: Optional[str]
    state: Optional[str]
    sub_parties: Optional[List['Party']]
    type: Optional[TypeEnum]
    zipcode: Optional[str]

    @staticmethod
    def from_dict(obj: Any) -> 'Party':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        address = from_union([from_str, from_none], obj.get("address"))
        city = from_union([from_str, from_none], obj.get("city"))
        name = from_union([from_str, from_none], obj.get("name"))
        notes = from_union([Note.from_dict, from_none], obj.get("notes"))
        phone = from_union([from_str, from_none], obj.get("phone"))
        state = from_union([from_str, from_none], obj.get("state"))
        sub_parties = from_union([lambda x: from_list(Party.from_dict, x), from_none], obj.get("subParties"))
        type = from_union([TypeEnum, from_none], obj.get("type"))
        zipcode = from_union([from_str, from_none], obj.get("zipcode"))
        return Party(error, id, created_by, created_date, last_modified_by, modified_date, address, city, name, notes, phone, state, sub_parties, type, zipcode)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["address"] = from_union([from_str, from_none], self.address)
        result["city"] = from_union([from_str, from_none], self.city)
        result["name"] = from_union([from_str, from_none], self.name)
        result["notes"] = from_union([lambda x: to_class(Note, x), from_none], self.notes)
        result["phone"] = from_union([from_str, from_none], self.phone)
        result["state"] = from_union([from_str, from_none], self.state)
        result["subParties"] = from_union([lambda x: from_list(lambda x: to_class(Party, x), x), from_none], self.sub_parties)
        result["type"] = from_union([lambda x: to_enum(TypeEnum, x), from_none], self.type)
        result["zipcode"] = from_union([from_str, from_none], self.zipcode)
        return result


class LeaseType(Enum):
    GROSS = "gross"
    N = "N"
    NN = "NN"
    NNN = "NNN"
    OPTION = "option"


class TermUnit(Enum):
    MONTHS = "months"
    QUARTERS = "quarters"
    YEARS = "years"


@dataclass
class Lease:
    """A lease for one or more properties"""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    description: Optional[str]
    lease_type: Optional[LeaseType]
    lessees: Optional[List[OID]]
    notes: Optional[List[Note]]
    rate: Optional[float]
    start_date: Optional[datetime]
    term_length: Optional[float]
    term_unit: Optional[TermUnit]

    @staticmethod
    def from_dict(obj: Any) -> 'Lease':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        description = from_union([from_str, from_none], obj.get("description"))
        lease_type = from_union([LeaseType, from_none], obj.get("leaseType"))
        lessees = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("lessees"))
        notes = from_union([lambda x: from_list(Note.from_dict, x), from_none], obj.get("notes"))
        rate = from_union([from_float, from_none], obj.get("rate"))
        start_date = from_union([from_datetime, from_none], obj.get("startDate"))
        term_length = from_union([from_float, from_none], obj.get("termLength"))
        term_unit = from_union([TermUnit, from_none], obj.get("termUnit"))
        return Lease(error, id, created_by, created_date, last_modified_by, modified_date, description, lease_type, lessees, notes, rate, start_date, term_length, term_unit)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["description"] = from_union([from_str, from_none], self.description)
        result["leaseType"] = from_union([lambda x: to_enum(LeaseType, x), from_none], self.lease_type)
        result["lessees"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.lessees)
        result["notes"] = from_union([lambda x: from_list(lambda x: to_class(Note, x), x), from_none], self.notes)
        result["rate"] = from_union([to_float, from_none], self.rate)
        result["startDate"] = from_union([lambda x: x.isoformat(), from_none], self.start_date)
        result["termLength"] = from_union([to_float, from_none], self.term_length)
        result["termUnit"] = from_union([lambda x: to_enum(TermUnit, x), from_none], self.term_unit)
        return result


@dataclass
class User:
    """A user in the system"""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    email: Optional[str]
    first_name: Optional[str]
    last_name: Optional[str]
    username: Optional[str]

    @staticmethod
    def from_dict(obj: Any) -> 'User':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        email = from_union([from_str, from_none], obj.get("email"))
        first_name = from_union([from_str, from_none], obj.get("firstName"))
        last_name = from_union([from_str, from_none], obj.get("lastName"))
        username = from_union([from_str, from_none], obj.get("username"))
        return User(error, id, created_by, created_date, last_modified_by, modified_date, email, first_name, last_name, username)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["email"] = from_union([from_str, from_none], self.email)
        result["firstName"] = from_union([from_str, from_none], self.first_name)
        result["lastName"] = from_union([from_str, from_none], self.last_name)
        result["username"] = from_union([from_str, from_none], self.username)
        return result


@dataclass
class MongoDoc:
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]

    @staticmethod
    def from_dict(obj: Any) -> 'MongoDoc':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        return MongoDoc(error, id, created_by, created_date, last_modified_by, modified_date)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        return result


@dataclass
class Metadata:
    description: Optional[str]
    tags: Optional[List[str]]

    @staticmethod
    def from_dict(obj: Any) -> 'Metadata':
        assert isinstance(obj, dict)
        description = from_union([from_str, from_none], obj.get("description"))
        tags = from_union([lambda x: from_list(from_str, x), from_none], obj.get("tags"))
        return Metadata(description, tags)

    def to_dict(self) -> dict:
        result: dict = {}
        result["description"] = from_union([from_str, from_none], self.description)
        result["tags"] = from_union([lambda x: from_list(from_str, x), from_none], self.tags)
        return result


@dataclass
class Media:
    """A media file that is associated with a property, lease, note, etc."""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    chunk_size: Optional[float]
    content_type: Optional[str]
    filename: Optional[str]
    length: Optional[float]
    md5: Optional[str]
    upload_date: Optional[datetime]
    metadata: Optional[Metadata]

    @staticmethod
    def from_dict(obj: Any) -> 'Media':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        chunk_size = from_union([from_float, from_none], obj.get("chunkSize"))
        content_type = from_union([from_str, from_none], obj.get("contentType"))
        filename = from_union([from_str, from_none], obj.get("filename"))
        length = from_union([from_float, from_none], obj.get("length"))
        md5 = from_union([from_str, from_none], obj.get("md5"))
        upload_date = from_union([from_datetime, from_none], obj.get("uploadDate"))
        metadata = from_union([Metadata.from_dict, from_none], obj.get("metadata"))
        return Media(error, id, created_by, created_date, last_modified_by, modified_date, chunk_size, content_type, filename, length, md5, upload_date, metadata)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["chunkSize"] = from_union([to_float, from_none], self.chunk_size)
        result["contentType"] = from_union([from_str, from_none], self.content_type)
        result["filename"] = from_union([from_str, from_none], self.filename)
        result["length"] = from_union([to_float, from_none], self.length)
        result["md5"] = from_union([from_str, from_none], self.md5)
        result["uploadDate"] = from_union([lambda x: x.isoformat(), from_none], self.upload_date)
        result["metadata"] = from_union([lambda x: to_class(Metadata, x), from_none], self.metadata)
        return result


@dataclass
class Owner:
    id: Optional[OID]
    portion: Optional[int]

    @staticmethod
    def from_dict(obj: Any) -> 'Owner':
        assert isinstance(obj, dict)
        id = from_union([OID.from_dict, from_none], obj.get("id"))
        portion = from_union([from_int, from_none], obj.get("portion"))
        return Owner(id, portion)

    def to_dict(self) -> dict:
        result: dict = {}
        result["id"] = from_union([lambda x: to_class(OID, x), from_none], self.id)
        result["portion"] = from_union([from_int, from_none], self.portion)
        return result


class PropType(Enum):
    COMMERCIAL = "commercial"
    INDUSTRIAL = "industrial"
    LAND = "land"
    RESIDENTIAL = "residential"


@dataclass
class LineItem:
    amount_cents: Optional[float]
    description: Optional[str]

    @staticmethod
    def from_dict(obj: Any) -> 'LineItem':
        assert isinstance(obj, dict)
        amount_cents = from_union([from_float, from_none], obj.get("amountCents"))
        description = from_union([from_str, from_none], obj.get("description"))
        return LineItem(amount_cents, description)

    def to_dict(self) -> dict:
        result: dict = {}
        result["amountCents"] = from_union([to_float, from_none], self.amount_cents)
        result["description"] = from_union([from_str, from_none], self.description)
        return result


@dataclass
class Payment:
    amount_cents: Optional[float]
    payment_date: Optional[datetime]

    @staticmethod
    def from_dict(obj: Any) -> 'Payment':
        assert isinstance(obj, dict)
        amount_cents = from_union([from_float, from_none], obj.get("amountCents"))
        payment_date = from_union([from_datetime, from_none], obj.get("paymentDate"))
        return Payment(amount_cents, payment_date)

    def to_dict(self) -> dict:
        result: dict = {}
        result["amountCents"] = from_union([to_float, from_none], self.amount_cents)
        result["paymentDate"] = from_union([lambda x: x.isoformat(), from_none], self.payment_date)
        return result


@dataclass
class TaxBill:
    building_assessed_cents: Optional[float]
    due_date: Optional[datetime]
    land_assessed_cents: Optional[float]
    line_items: Optional[List[LineItem]]
    misc_assessed_cents: Optional[float]
    payments: Optional[List[Payment]]
    total_assessed_cents: Optional[float]

    @staticmethod
    def from_dict(obj: Any) -> 'TaxBill':
        assert isinstance(obj, dict)
        building_assessed_cents = from_union([from_float, from_none], obj.get("buildingAssessedCents"))
        due_date = from_union([from_datetime, from_none], obj.get("dueDate"))
        land_assessed_cents = from_union([from_float, from_none], obj.get("landAssessedCents"))
        line_items = from_union([lambda x: from_list(LineItem.from_dict, x), from_none], obj.get("lineItems"))
        misc_assessed_cents = from_union([from_float, from_none], obj.get("miscAssessedCents"))
        payments = from_union([lambda x: from_list(Payment.from_dict, x), from_none], obj.get("payments"))
        total_assessed_cents = from_union([from_float, from_none], obj.get("totalAssessedCents"))
        return TaxBill(building_assessed_cents, due_date, land_assessed_cents, line_items, misc_assessed_cents, payments, total_assessed_cents)

    def to_dict(self) -> dict:
        result: dict = {}
        result["buildingAssessedCents"] = from_union([to_float, from_none], self.building_assessed_cents)
        result["dueDate"] = from_union([lambda x: x.isoformat(), from_none], self.due_date)
        result["landAssessedCents"] = from_union([to_float, from_none], self.land_assessed_cents)
        result["lineItems"] = from_union([lambda x: from_list(lambda x: to_class(LineItem, x), x), from_none], self.line_items)
        result["miscAssessedCents"] = from_union([to_float, from_none], self.misc_assessed_cents)
        result["payments"] = from_union([lambda x: from_list(lambda x: to_class(Payment, x), x), from_none], self.payments)
        result["totalAssessedCents"] = from_union([to_float, from_none], self.total_assessed_cents)
        return result


@dataclass
class TaxPropInfo:
    assessment_date: Optional[datetime]
    building_appraised_cents: Optional[float]
    land_appraised_cents: Optional[float]
    legal_description: Optional[str]
    misc_appraised_cents: Optional[float]
    neighborhood: Optional[str]
    owner_address: Optional[str]
    owner_name: Optional[str]
    property_class: Optional[str]
    situs_address: Optional[str]
    tax_district: Optional[str]
    total_appraised_cents: Optional[float]
    zoning: Optional[str]

    @staticmethod
    def from_dict(obj: Any) -> 'TaxPropInfo':
        assert isinstance(obj, dict)
        assessment_date = from_union([from_datetime, from_none], obj.get("assessmentDate"))
        building_appraised_cents = from_union([from_float, from_none], obj.get("buildingAppraisedCents"))
        land_appraised_cents = from_union([from_float, from_none], obj.get("landAppraisedCents"))
        legal_description = from_union([from_str, from_none], obj.get("legalDescription"))
        misc_appraised_cents = from_union([from_float, from_none], obj.get("miscAppraisedCents"))
        neighborhood = from_union([from_str, from_none], obj.get("neighborhood"))
        owner_address = from_union([from_str, from_none], obj.get("ownerAddress"))
        owner_name = from_union([from_str, from_none], obj.get("ownerName"))
        property_class = from_union([from_str, from_none], obj.get("propertyClass"))
        situs_address = from_union([from_str, from_none], obj.get("situsAddress"))
        tax_district = from_union([from_str, from_none], obj.get("taxDistrict"))
        total_appraised_cents = from_union([from_float, from_none], obj.get("totalAppraisedCents"))
        zoning = from_union([from_str, from_none], obj.get("zoning"))
        return TaxPropInfo(assessment_date, building_appraised_cents, land_appraised_cents, legal_description, misc_appraised_cents, neighborhood, owner_address, owner_name, property_class, situs_address, tax_district, total_appraised_cents, zoning)

    def to_dict(self) -> dict:
        result: dict = {}
        result["assessmentDate"] = from_union([lambda x: x.isoformat(), from_none], self.assessment_date)
        result["buildingAppraisedCents"] = from_union([to_float, from_none], self.building_appraised_cents)
        result["landAppraisedCents"] = from_union([to_float, from_none], self.land_appraised_cents)
        result["legalDescription"] = from_union([from_str, from_none], self.legal_description)
        result["miscAppraisedCents"] = from_union([to_float, from_none], self.misc_appraised_cents)
        result["neighborhood"] = from_union([from_str, from_none], self.neighborhood)
        result["ownerAddress"] = from_union([from_str, from_none], self.owner_address)
        result["ownerName"] = from_union([from_str, from_none], self.owner_name)
        result["propertyClass"] = from_union([from_str, from_none], self.property_class)
        result["situsAddress"] = from_union([from_str, from_none], self.situs_address)
        result["taxDistrict"] = from_union([from_str, from_none], self.tax_district)
        result["totalAppraisedCents"] = from_union([to_float, from_none], self.total_appraised_cents)
        result["zoning"] = from_union([from_str, from_none], self.zoning)
        return result


@dataclass
class Property:
    """A set of one or more parcels that constitute a single logic piece of real estate"""
    """A placeholder where errors concerning the object can go"""
    error: Optional[str]
    id: OID
    """The id of the user that created this object"""
    created_by: Optional[OID]
    """The date the object was first created"""
    created_date: Optional[datetime]
    """The id of the user that last modified this object"""
    last_modified_by: Optional[OID]
    """The date of the last update to the object"""
    modified_date: Optional[datetime]
    acreage: Optional[float]
    """WKT of the boundary of the property"""
    boundary: Optional[str]
    contact_ids: Optional[List[OID]]
    county: Optional[str]
    description: Optional[str]
    desired_rent_cents: Optional[float]
    desired_sales_price_dollars: Optional[float]
    insurance_policy_ids: Optional[List[OID]]
    latitude: Optional[float]
    lease_ids: Optional[List[OID]]
    longitude: Optional[float]
    media_ids: Optional[List[OID]]
    name: Optional[str]
    note_ids: Optional[List[OID]]
    owners: Optional[List[Owner]]
    pin_numbers: Optional[List[str]]
    prop_type: Optional[PropType]
    state: Optional[str]
    tags: Optional[List[str]]
    tax_bills: Optional[Dict[str, Dict[str, TaxBill]]]
    tax_prop_info: Optional[Dict[str, TaxPropInfo]]
    tax_refresh_requested: Optional[bool]

    @staticmethod
    def from_dict(obj: Any) -> 'Property':
        assert isinstance(obj, dict)
        error = from_union([from_str, from_none], obj.get("_error"))
        id = OID.from_dict(obj.get("_id"))
        created_by = from_union([OID.from_dict, from_none], obj.get("createdBy"))
        created_date = from_union([from_datetime, from_none], obj.get("createdDate"))
        last_modified_by = from_union([OID.from_dict, from_none], obj.get("lastModifiedBy"))
        modified_date = from_union([from_datetime, from_none], obj.get("modifiedDate"))
        acreage = from_union([from_float, from_none], obj.get("acreage"))
        boundary = from_union([from_str, from_none], obj.get("boundary"))
        contact_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("contactIds"))
        county = from_union([from_str, from_none], obj.get("county"))
        description = from_union([from_str, from_none], obj.get("description"))
        desired_rent_cents = from_union([from_float, from_none], obj.get("desiredRentCents"))
        desired_sales_price_dollars = from_union([from_float, from_none], obj.get("desiredSalesPriceDollars"))
        insurance_policy_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("insurancePolicyIds"))
        latitude = from_union([from_float, from_none], obj.get("latitude"))
        lease_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("leaseIds"))
        longitude = from_union([from_float, from_none], obj.get("longitude"))
        media_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("mediaIds"))
        name = from_union([from_str, from_none], obj.get("name"))
        note_ids = from_union([lambda x: from_list(OID.from_dict, x), from_none], obj.get("noteIds"))
        owners = from_union([lambda x: from_list(Owner.from_dict, x), from_none], obj.get("owners"))
        pin_numbers = from_union([lambda x: from_list(from_str, x), from_none], obj.get("pinNumbers"))
        prop_type = from_union([PropType, from_none], obj.get("propType"))
        state = from_union([from_str, from_none], obj.get("state"))
        tags = from_union([lambda x: from_list(from_str, x), from_none], obj.get("tags"))
        tax_bills = from_union([lambda x: from_dict(lambda x: from_dict(TaxBill.from_dict, x), x), from_none], obj.get("taxBills"))
        tax_prop_info = from_union([lambda x: from_dict(TaxPropInfo.from_dict, x), from_none], obj.get("taxPropInfo"))
        tax_refresh_requested = from_union([from_bool, from_none], obj.get("taxRefreshRequested"))
        return Property(error, id, created_by, created_date, last_modified_by, modified_date, acreage, boundary, contact_ids, county, description, desired_rent_cents, desired_sales_price_dollars, insurance_policy_ids, latitude, lease_ids, longitude, media_ids, name, note_ids, owners, pin_numbers, prop_type, state, tags, tax_bills, tax_prop_info, tax_refresh_requested)

    def to_dict(self) -> dict:
        result: dict = {}
        result["_error"] = from_union([from_str, from_none], self.error)
        result["_id"] = to_class(OID, self.id)
        result["createdBy"] = from_union([lambda x: to_class(OID, x), from_none], self.created_by)
        result["createdDate"] = from_union([lambda x: x.isoformat(), from_none], self.created_date)
        result["lastModifiedBy"] = from_union([lambda x: to_class(OID, x), from_none], self.last_modified_by)
        result["modifiedDate"] = from_union([lambda x: x.isoformat(), from_none], self.modified_date)
        result["acreage"] = from_union([to_float, from_none], self.acreage)
        result["boundary"] = from_union([from_str, from_none], self.boundary)
        result["contactIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.contact_ids)
        result["county"] = from_union([from_str, from_none], self.county)
        result["description"] = from_union([from_str, from_none], self.description)
        result["desiredRentCents"] = from_union([to_float, from_none], self.desired_rent_cents)
        result["desiredSalesPriceDollars"] = from_union([to_float, from_none], self.desired_sales_price_dollars)
        result["insurancePolicyIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.insurance_policy_ids)
        result["latitude"] = from_union([to_float, from_none], self.latitude)
        result["leaseIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.lease_ids)
        result["longitude"] = from_union([to_float, from_none], self.longitude)
        result["mediaIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.media_ids)
        result["name"] = from_union([from_str, from_none], self.name)
        result["noteIds"] = from_union([lambda x: from_list(lambda x: to_class(OID, x), x), from_none], self.note_ids)
        result["owners"] = from_union([lambda x: from_list(lambda x: to_class(Owner, x), x), from_none], self.owners)
        result["pinNumbers"] = from_union([lambda x: from_list(from_str, x), from_none], self.pin_numbers)
        result["propType"] = from_union([lambda x: to_enum(PropType, x), from_none], self.prop_type)
        result["state"] = from_union([from_str, from_none], self.state)
        result["tags"] = from_union([lambda x: from_list(from_str, x), from_none], self.tags)
        result["taxBills"] = from_union([lambda x: from_dict(lambda x: from_dict(lambda x: to_class(TaxBill, x), x), x), from_none], self.tax_bills)
        result["taxPropInfo"] = from_union([lambda x: from_dict(lambda x: to_class(TaxPropInfo, x), x), from_none], self.tax_prop_info)
        result["taxRefreshRequested"] = from_union([from_bool, from_none], self.tax_refresh_requested)
        return result


class CollectionName(Enum):
    """A set of Mongo collection names for the various models"""
    LEASES = "leases"
    MEDIA_FILES = "media.files"
    NOTES = "notes"
    PARTIES = "parties"
    PROPERTIES = "properties"
    USERS = "users"


def insurance_policy_from_dict(s: Any) -> InsurancePolicy:
    return InsurancePolicy.from_dict(s)


def insurance_policy_to_dict(x: InsurancePolicy) -> Any:
    return to_class(InsurancePolicy, x)


def party_from_dict(s: Any) -> Party:
    return Party.from_dict(s)


def party_to_dict(x: Party) -> Any:
    return to_class(Party, x)


def lease_from_dict(s: Any) -> Lease:
    return Lease.from_dict(s)


def lease_to_dict(x: Lease) -> Any:
    return to_class(Lease, x)


def user_from_dict(s: Any) -> User:
    return User.from_dict(s)


def user_to_dict(x: User) -> Any:
    return to_class(User, x)


def mongo_doc_from_dict(s: Any) -> MongoDoc:
    return MongoDoc.from_dict(s)


def mongo_doc_to_dict(x: MongoDoc) -> Any:
    return to_class(MongoDoc, x)


def media_from_dict(s: Any) -> Media:
    return Media.from_dict(s)


def media_to_dict(x: Media) -> Any:
    return to_class(Media, x)


def property_from_dict(s: Any) -> Property:
    return Property.from_dict(s)


def property_to_dict(x: Property) -> Any:
    return to_class(Property, x)


def common_from_dict(s: Any) -> Any:
    return s


def common_to_dict(x: Any) -> Any:
    return x


def note_from_dict(s: Any) -> Note:
    return Note.from_dict(s)


def note_to_dict(x: Note) -> Any:
    return to_class(Note, x)


def collection_name_from_dict(s: Any) -> CollectionName:
    return CollectionName(s)


def collection_name_to_dict(x: CollectionName) -> Any:
    return to_enum(CollectionName, x)
