/*
 * THIS FILE IS GENERATED FROM models/generate.sh
 * DO NOT EDIT THIS FILE!
 */
// tslint:disable

import { ObjectID } from "bson";

/**
 * A set of Mongo collection names for the various models
 */
export enum CollectionName {
    InsurancePolicies = "insurancePolicies",
    Leases = "leases",
    MediaFiles = "media.files",
    Notes = "notes",
    Parties = "parties",
    Properties = "properties",
    Users = "users",
}

/**
 * An insurance policy that applies to one or more properties
 */
export interface InsurancePolicy {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    description?:  string;
    endDate?:      Date;
    mediaIds?:     ObjectID[];
    startDate?:    Date;
}

/**
 * A JSON-encoded BSON ObjectId
 *
 * The id of the user that created this object
 *
 * The id of the user that last modified this object
 */
export interface OID {
    $oid: string;
}

/**
 * An issue on a property
 */
export interface Issue {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    description?:  string;
    mediaIds?:     ObjectID[];
    tags?:         string[];
    title?:        string;
    updates?:      Note[];
}

/**
 * A note that gives an update on an item
 */
export interface Note {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    media?:        ObjectID[];
    note?:         string;
    pinned?:       boolean;
    title?:        string;
}

/**
 * A lease for one or more properties
 */
export interface Lease {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    description?:  string;
    leaseType?:    LeaseType;
    lessees?:      ObjectID[];
    notes?:        Note[];
    rate?:         number;
    startDate?:    Date;
    termLength?:   number;
    termUnit?:     TermUnit;
}

export enum LeaseType {
    Gross = "gross",
    N = "N",
    Nn = "NN",
    Nnn = "NNN",
    Option = "option",
}

export enum TermUnit {
    Months = "months",
    Quarters = "quarters",
    Years = "years",
}

/**
 * A media file that is associated with a property, lease, note, etc.
 */
export interface Media {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    chunkSize?:    number;
    contentType?:  string;
    filename?:     string;
    length?:       number;
    md5?:          string;
    uploadDate?:   Date;
    metadata?:     Metadata;
}

export interface Metadata {
    description?: string;
    tags?:        string[];
}

export interface MongoDoc {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
}

/**
 * A person or organization/company that interacts with real estate in some way, e.g. owner,
 * lessee, contractors, etc.
 */
export interface Party {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?: Date;
    address?:      string;
    city?:         string;
    description?:  string;
    name?:         string;
    phone?:        string;
    state?:        string;
    subParties?:   Party[];
    type?:         Type;
    zipcode?:      string;
}

export enum Type {
    Company = "company",
    Person = "person",
}

/**
 * A set of one or more parcels that constitute a single logic piece of real estate
 */
export interface Property {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?:             Date;
    acreage?:                  number;
    city?:                     string;
    contactIds?:               ObjectID[];
    county?:                   string;
    description?:              string;
    desiredRentCents?:         number;
    desiredSalesPriceDollars?: number;
    insurancePolicyIds?:       ObjectID[];
    leaseIds?:                 ObjectID[];
    mediaIds?:                 ObjectID[];
    name?:                     string;
    noteIds?:                  ObjectID[];
    owners?:                   Owner[];
    parcelData?:               { [key: string]: ParcelDatum };
    /**
     * If set to true, the GIS parcel information for this property should be refreshed
     */
    parcelDataRefreshRequested?: boolean;
    pinNumbers?:                 string[];
    propType?:                   PropType;
    state?:                      string;
    tags?:                       string[];
    taxBills?:                   { [key: string]: { [key: string]: TaxBill } };
    taxPropInfo?:                { [key: string]: TaxPropInfo };
    taxRefreshRequested?:        boolean;
}

export interface Owner {
    id?:      ObjectID;
    portion?: number;
}

export interface ParcelDatum {
    acreage?:       number;
    boundaryWKT?:   string;
    ownerName?:     string;
    streetAddress?: string;
}

export enum PropType {
    Commercial = "commercial",
    Industrial = "industrial",
    Land = "land",
    Residential = "residential",
}

export interface TaxBill {
    buildingAssessedCents?: number;
    dueDate?:               Date;
    landAssessedCents?:     number;
    lineItems?:             LineItem[];
    miscAssessedCents?:     number;
    payments?:              Payment[];
    totalAssessedCents?:    number;
}

export interface LineItem {
    amountCents?: number;
    description?: string;
}

export interface Payment {
    amountCents?: number;
    paymentDate?: Date;
}

export interface TaxPropInfo {
    assessmentDate?:         Date;
    buildingAppraisedCents?: number;
    landAppraisedCents?:     number;
    legalDescription?:       string;
    miscAppraisedCents?:     number;
    neighborhood?:           string;
    ownerAddress?:           string;
    ownerName?:              string;
    propertyClass?:          string;
    situsAddress?:           string;
    taxDistrict?:            string;
    totalAppraisedCents?:    number;
    zoning?:                 string;
}

/**
 * A user in the system
 */
export interface User {
    /**
     * A placeholder where errors concerning the object can go
     */
    _error?: string;
    _id:     ObjectID;
    /**
     * The id of the user that created this object
     */
    createdBy?: ObjectID;
    /**
     * The date the object was first created
     */
    createdDate?: Date;
    /**
     * The id of the user that last modified this object
     */
    lastModifiedBy?: ObjectID;
    /**
     * The date of the last update to the object
     */
    modifiedDate?:   Date;
    disabled:        boolean;
    email?:          string;
    firstName?:      string;
    lastName?:       string;
    passwordHashed?: string;
    sessionIds?:     string[];
    username:        string;
}
