#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

TAG=dev make images

helm upgrade --install --set webapp.distDir=$(cd ${SCRIPT_DIR}/../webapp/dist; pwd) --values dev/helm-dev.yaml remdev helm/rem
