#!/bin/bash

# Resets the Mongo database and loads development fixtures in the cluster currently configured with
# kubectl

set -exuo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/..

PUSH=yes TAG=dev make mongo-dev-fixtures

kubectl exec mongo-0 -- mongo rem --eval 'db.dropDatabase();'
kubectl exec mongo-0 -- /opt/setup/run.sh
kubectl run dev-fixtures -i -t --rm --image-pull-policy=Always --restart=Never --image quay.io/rem/mongo-dev-fixtures:dev -- /opt/dev/load-fixtures.sh
