#!/bin/bash

# Resets the Mongo database and loads development fixtures in the cluster currently configured with
# kubectl

set -exuo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SCRIPT_DIR/..

kubectl_run_flags="-i -t --rm --restart=Never"

TAG=dev make mongo-dev-fixtures

kubectl exec -it mongo-0 -- mongo rem --eval 'db.dropDatabase();'
kubectl exec mongo-0 -- /opt/setup/run.sh
kubectl run dev-fixtures $kubectl_run_flags --image quay.io/rem/mongo-dev-fixtures -- /opt/dev/load-fixtures.sh
