# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gis.proto',
  package='gis',
  syntax='proto3',
  serialized_pb=_b('\n\tgis.proto\x12\x03gis\"B\n\rParcelRequest\x12\x12\n\npin_number\x18\x01 \x01(\t\x12\x0e\n\x06\x63ounty\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\"{\n\nParcelData\x12\x12\n\npin_number\x18\x01 \x01(\t\x12\x12\n\nowner_name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63reage\x18\x03 \x01(\x01\x12\x16\n\x0estreet_address\x18\x04 \x01(\t\x12\x1c\n\x14\x62oundary_polygon_wkt\x18\x05 \x01(\t2=\n\x03GIS\x12\x36\n\rGetParcelInfo\x12\x12.gis.ParcelRequest\x1a\x0f.gis.ParcelData\"\x00\x62\x06proto3')
)




_PARCELREQUEST = _descriptor.Descriptor(
  name='ParcelRequest',
  full_name='gis.ParcelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin_number', full_name='gis.ParcelRequest.pin_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='county', full_name='gis.ParcelRequest.county', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='gis.ParcelRequest.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=84,
)


_PARCELDATA = _descriptor.Descriptor(
  name='ParcelData',
  full_name='gis.ParcelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pin_number', full_name='gis.ParcelData.pin_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_name', full_name='gis.ParcelData.owner_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acreage', full_name='gis.ParcelData.acreage', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street_address', full_name='gis.ParcelData.street_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boundary_polygon_wkt', full_name='gis.ParcelData.boundary_polygon_wkt', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=209,
)

DESCRIPTOR.message_types_by_name['ParcelRequest'] = _PARCELREQUEST
DESCRIPTOR.message_types_by_name['ParcelData'] = _PARCELDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParcelRequest = _reflection.GeneratedProtocolMessageType('ParcelRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARCELREQUEST,
  __module__ = 'gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.ParcelRequest)
  ))
_sym_db.RegisterMessage(ParcelRequest)

ParcelData = _reflection.GeneratedProtocolMessageType('ParcelData', (_message.Message,), dict(
  DESCRIPTOR = _PARCELDATA,
  __module__ = 'gis_pb2'
  # @@protoc_insertion_point(class_scope:gis.ParcelData)
  ))
_sym_db.RegisterMessage(ParcelData)



_GIS = _descriptor.ServiceDescriptor(
  name='GIS',
  full_name='gis.GIS',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=211,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetParcelInfo',
    full_name='gis.GIS.GetParcelInfo',
    index=0,
    containing_service=None,
    input_type=_PARCELREQUEST,
    output_type=_PARCELDATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GIS)

DESCRIPTOR.services_by_name['GIS'] = _GIS

# @@protoc_insertion_point(module_scope)
