# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gis_pb2 as gis__pb2


class GISStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetParcelInfo = channel.unary_unary(
        '/gis.GIS/GetParcelInfo',
        request_serializer=gis__pb2.ParcelRequest.SerializeToString,
        response_deserializer=gis__pb2.ParcelData.FromString,
        )


class GISServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetParcelInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GISServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetParcelInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetParcelInfo,
          request_deserializer=gis__pb2.ParcelRequest.FromString,
          response_serializer=gis__pb2.ParcelData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gis.GIS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
