#!/usr/bin/env python3

import re
import sys

from parcel_data import adapter
from shapely.wkt import loads

county, state, pin_number = sys.argv[1:4]
parcel = adapter.get_parcel_data_by_pin(county, state, pin_number)

print("Owner: %s" % parcel.owner_name)
print("Acreage: %s" % parcel.acreage)

def coords_to_str(coords):
    return "\n".join("%s, %s" % (t[1], t[0]) for t in coords)

boundaries = []
geom = loads(parcel.boundary_wkt)
if geom.type == 'MultiPolygon':
    for g in geom.geoms:
        boundaries.append(coords_to_str(g.exterior.coords))
else:
    boundaries.append(coords_to_str(geom.exterior.coords))

print("Boundary Points:\n%s" % "\n\n".join(boundaries))
