# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tax_pb2 as tax__pb2


class TaxInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTaxBills = channel.unary_unary(
        '/tax.TaxInfo/GetTaxBills',
        request_serializer=tax__pb2.ParcelTaxRequest.SerializeToString,
        response_deserializer=tax__pb2.ParcelTaxBills.FromString,
        )


class TaxInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetTaxBills(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TaxInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTaxBills': grpc.unary_unary_rpc_method_handler(
          servicer.GetTaxBills,
          request_deserializer=tax__pb2.ParcelTaxRequest.FromString,
          response_serializer=tax__pb2.ParcelTaxBills.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tax.TaxInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
