package gocommon

// THIS FILE IS GENERATED FROM models/generate.sh
// DO NOT EDIT THIS FILE!

type Common interface{}

// An insurance policy that applies to one or more properties
type InsurancePolicy struct {
	Error          *string `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID     `json:"_id"`
	CreatedBy      *OID    `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID    `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Description    *string `json:"description,omitempty"`
	EndDate        *string `json:"endDate,omitempty"`
	MediaIDS       []OID   `json:"mediaIds"`
	StartDate      *string `json:"startDate,omitempty"`
}

// A JSON-encoded BSON ObjectId
//
// The id of the user that created this object
//
// The id of the user that last modified this object
type OID struct {
	OID string `json:"$oid"`
}

// A person or organization/company that interacts with real estate in some way, e.g. owner,
// lessee, contractors, etc.
type Party struct {
	Error          *string `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID     `json:"_id"`
	CreatedBy      *OID    `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID    `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Address        *string `json:"address,omitempty"`
	City           *string `json:"city,omitempty"`
	Name           *string `json:"name,omitempty"`
	Notes          *Note   `json:"notes,omitempty"`
	Phone          *string `json:"phone,omitempty"`
	State          *string `json:"state,omitempty"`
	SubParties     []Party `json:"subParties"`
	Type           *Type   `json:"type,omitempty"`
	Zipcode        *string `json:"zipcode,omitempty"`
}

// A note that gives an update on an item
type Note struct {
	Error          *string `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID     `json:"_id"`
	CreatedBy      *OID    `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID    `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Media          []OID   `json:"media"`
	Note           *string `json:"note,omitempty"`
	Title          *string `json:"title,omitempty"`
}

// A lease for one or more properties
type Lease struct {
	Error          *string    `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID        `json:"_id"`
	CreatedBy      *OID       `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string    `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID       `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string    `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Description    *string    `json:"description,omitempty"`
	LeaseType      *LeaseType `json:"leaseType,omitempty"`
	Lessees        []OID      `json:"lessees"`
	Notes          []Note     `json:"notes"`
	Rate           *float64   `json:"rate,omitempty"`
	StartDate      *string    `json:"startDate,omitempty"`
	TermLength     *float64   `json:"termLength,omitempty"`
	TermUnit       *TermUnit  `json:"termUnit,omitempty"`
}

// A user in the system
type User struct {
	Error          *string `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID     `json:"_id"`
	CreatedBy      *OID    `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID    `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Email          *string `json:"email,omitempty"`
	FirstName      *string `json:"firstName,omitempty"`
	LastName       *string `json:"lastName,omitempty"`
	Username       *string `json:"username,omitempty"`
}

type MongoDoc struct {
	Error          *string `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID     `json:"_id"`
	CreatedBy      *OID    `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID    `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string `json:"modifiedDate,omitempty"`   // The date of the last update to the object
}

// A media file that is associated with a property, lease, note, etc.
type Media struct {
	Error          *string   `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID             OID       `json:"_id"`
	CreatedBy      *OID      `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate    *string   `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy *OID      `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate   *string   `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	ChunkSize      *float64  `json:"chunkSize,omitempty"`
	ContentType    *string   `json:"contentType,omitempty"`
	Filename       *string   `json:"filename,omitempty"`
	Length         *float64  `json:"length,omitempty"`
	Md5            *string   `json:"md5,omitempty"`
	UploadDate     *string   `json:"uploadDate,omitempty"`
	Metadata       *Metadata `json:"metadata,omitempty"`
}

type Metadata struct {
	Description *string  `json:"description,omitempty"`
	Tags        []string `json:"tags"`
}

// A set of one or more parcels that constitute a single logic piece of real estate
type Property struct {
	Error                    *string                       `json:"_error,omitempty"` // A placeholder where errors concerning the object can go
	ID                       OID                           `json:"_id"`
	CreatedBy                *OID                          `json:"createdBy,omitempty"`      // The id of the user that created this object
	CreatedDate              *string                       `json:"createdDate,omitempty"`    // The date the object was first created
	LastModifiedBy           *OID                          `json:"lastModifiedBy,omitempty"` // The id of the user that last modified this object
	ModifiedDate             *string                       `json:"modifiedDate,omitempty"`   // The date of the last update to the object
	Acreage                  *float64                      `json:"acreage,omitempty"`
	Boundary                 *string                       `json:"boundary,omitempty"` // WKT of the boundary of the property
	ContactIDS               []OID                         `json:"contactIds"`
	County                   *string                       `json:"county,omitempty"`
	Description              *string                       `json:"description,omitempty"`
	DesiredRentCents         *float64                      `json:"desiredRentCents,omitempty"`
	DesiredSalesPriceDollars *float64                      `json:"desiredSalesPriceDollars,omitempty"`
	InsurancePolicyIDS       []OID                         `json:"insurancePolicyIds"`
	Latitude                 *float64                      `json:"latitude,omitempty"`
	LeaseIDS                 []OID                         `json:"leaseIds"`
	Longitude                *float64                      `json:"longitude,omitempty"`
	MediaIDS                 []OID                         `json:"mediaIds"`
	Name                     *string                       `json:"name,omitempty"`
	NoteIDS                  []OID                         `json:"noteIds"`
	Owners                   []Owner                       `json:"owners"`
	PinNumbers               []string                      `json:"pinNumbers"`
	PropType                 *PropType                     `json:"propType,omitempty"`
	State                    *string                       `json:"state,omitempty"`
	Tags                     []string                      `json:"tags"`
	TaxBills                 map[string]map[string]TaxBill `json:"taxBills,omitempty"`
	TaxPropInfo              map[string]TaxPropInfo        `json:"taxPropInfo,omitempty"`
	TaxRefreshRequested      *bool                         `json:"taxRefreshRequested,omitempty"`
}

type Owner struct {
	ID      *OID   `json:"id,omitempty"`
	Portion *int64 `json:"portion,omitempty"`
}

type TaxBill struct {
	BuildingAssessedCents *float64   `json:"buildingAssessedCents,omitempty"`
	DueDate               *string    `json:"dueDate,omitempty"`
	LandAssessedCents     *float64   `json:"landAssessedCents,omitempty"`
	LineItems             []LineItem `json:"lineItems"`
	MiscAssessedCents     *float64   `json:"miscAssessedCents,omitempty"`
	Payments              []Payment  `json:"payments"`
	TotalAssessedCents    *float64   `json:"totalAssessedCents,omitempty"`
}

type LineItem struct {
	AmountCents *float64 `json:"amountCents,omitempty"`
	Description *string  `json:"description,omitempty"`
}

type Payment struct {
	AmountCents *float64 `json:"amountCents,omitempty"`
	PaymentDate *string  `json:"paymentDate,omitempty"`
}

type TaxPropInfo struct {
	AssessmentDate         *string  `json:"assessmentDate,omitempty"`
	BuildingAppraisedCents *float64 `json:"buildingAppraisedCents,omitempty"`
	LandAppraisedCents     *float64 `json:"landAppraisedCents,omitempty"`
	LegalDescription       *string  `json:"legalDescription,omitempty"`
	MiscAppraisedCents     *float64 `json:"miscAppraisedCents,omitempty"`
	Neighborhood           *string  `json:"neighborhood,omitempty"`
	OwnerAddress           *string  `json:"ownerAddress,omitempty"`
	OwnerName              *string  `json:"ownerName,omitempty"`
	PropertyClass          *string  `json:"propertyClass,omitempty"`
	SitusAddress           *string  `json:"situsAddress,omitempty"`
	TaxDistrict            *string  `json:"taxDistrict,omitempty"`
	TotalAppraisedCents    *float64 `json:"totalAppraisedCents,omitempty"`
	Zoning                 *string  `json:"zoning,omitempty"`
}

type Type string

const (
	Company Type = "company"
	Person  Type = "person"
)

type LeaseType string

const (
	Gross  LeaseType = "gross"
	N      LeaseType = "N"
	Nn     LeaseType = "NN"
	Nnn    LeaseType = "NNN"
	Option LeaseType = "option"
)

type TermUnit string

const (
	Months   TermUnit = "months"
	Quarters TermUnit = "quarters"
	Years    TermUnit = "years"
)

type PropType string

const (
	Commercial  PropType = "commercial"
	Industrial  PropType = "industrial"
	Land        PropType = "land"
	Residential PropType = "residential"
)

// A set of Mongo collection names for the various models
type CollectionName string

const (
	Leases     CollectionName = "leases"
	MediaFiles CollectionName = "media.files"
	Notes      CollectionName = "notes"
	Parties    CollectionName = "parties"
	Properties CollectionName = "properties"
	Users      CollectionName = "users"
)
