#!/bin/bash

set -ex

mkdir -p /data/sqlite
chown -R django.django /data/sqlite
chown -R django.django /media

if [[ -z $1 ]]
then
  python /app/manage.py migrate --noinput
  python /app/manage.py collectstatic --noinput

  exec gunicorn -c /app/docker/app/gunicorn-config.py rem.wsgi
else
  exec $@
fi
